version: "3"

services:

  hash-translator:
    build:
      context: hashtranslator-service
    restart: unless-stopped
    depends_on:
      - application-database
    ports:
      - "8081:8081"

  authorization-service:
    build:
      context: authorization-service
    restart: unless-stopped
    depends_on:
      - users-database
    ports:
      - "8080:8080"

  users-database:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    env_file:
      - authorization-service/environment/database.postgres.env
    ports:
      - "5432:5432"

  application-database:
    container_name: mongo
    image: mongo:4.2.23-rc1
    ports:
      - "27017:27017"
    restart: unless-stopped
