spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://users-database:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  flyway:
    user: postgres
    password: root
    url: jdbc:postgresql://users-database:5432/postgres
    baseline-version: 0
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history
    baseline-on-migrate: true

  application:
    name: authorization
server:
  error:
    include-message: always
